# Configuración para GitHub Pages
title: "Pedro Fabián Gutiérrez Vidrio - Data Analyst"
description: "Portafolio profesional de Analista de Datos especializado en Business Intelligence"
author: "Pedro Fabián Gutiérrez Vidrio"

# Desactivar Jekyll para usar HTML estático
plugins: []
